Feat:: Searchfield component 생성
sniperfactory-official/sfac-designkit-react pull request #42
Opened 2023-08-02 03:30 UTC by UichaeHong

## What is this PR?

> 어떤 기능 구현했는지 간단하게 명시

- [ ] 구현 기능 내역

## Changes

> 어떤 위험이나 장애가 발견되었는지
> 무슨 이유로 코드를 변경했는지

## Screenshot

> 관련 스크린샷

focus X
![image](https://github.com/sniperfactory-official/sfac-designkit-react/assets/127120819/fdcd2767-024b-4a29-9bee-76ce20c461a3)

focus O
![스크린샷 2023-08-01 195045](https://github.com/sniperfactory-official/sfac-designkit-react/assets/127120819/9a04f50b-827e-4218-a760-31fe5c06554c)

## Review point

> 어떤 부분에 리뷰어가 집중하면 좋을지(가이드라인 제시)

1. 삼항 연산자를 사용해서 focus 됐을 때와 안 됐을 때 다르게 나오도록 구현했습니다

2. textarea 컴포넌트와 동일하게 콜백함수로 호출하고 사용자가 입력한 값을 매개변수 전달하도록 만들어 사용 방법 또한 같습니다
```javascript
export default function Home() {
  const test = (value: string) => {
    console.log(value);
  };
  return (
    <>
      <Searchfield onChangeSearchfield={test} />
    </>
  );
}
```
## Challenge point

> 어려웠던 점 (선택사항)

2023-08-03 19:31 UTC, DoctorK4 approved these changes

2023-08-05 00:30 UTC, DoctorK4 requested changes
확장성있게 코드 변경 후 다시 PR 올려주세요!

2023-08-06 13:05 UTC, hayeonn2 approved these changes

2023-08-06 13:05 UTC, hayeonn2 commented on app/components/Searchfield/Searchfield.tsx
> +        >
이 부분 div보다 button 태그로 주는게 낫지 않을까용?

2023-08-06 14:16 UTC, DoctorK4 approved these changes

2023-08-06 14:22 UTC, merged