Feature/input 컴포넌트 생성
sniperfactory-official/sfac-designkit-react pull request #43
Opened 2023-08-02 04:03 UTC by UichaeHong

## What is this PR?

> 어떤 기능 구현했는지 간단하게 명시

- [ ] 구현 기능 내역

- [x] input 컴포넌트 생성

## Changes

> 어떤 위험이나 장애가 발견되었는지
> 무슨 이유로 코드를 변경했는지

## Screenshot

> 관련 스크린샷
![image](https://github.com/sniperfactory-official/sfac-designkit-react/assets/127120819/a25f92f8-83d8-4b7d-8deb-ed63be2a8760)
```javascript
export default function Home() {
  const test1 = (value: string) => {
    console.log(value);
  };
  const test2 = (value: string) => {
    console.log(value);
  };
  const test3 = (value: string) => {
    console.log(value);
  };
  return (
    <>
      <Input onChangeInputDefault={test1} />
      <Input mode="Text" onChangeInputText={test2} />
      <Input mode="Label" onChangeInputLabel={test3} />
    </>
  );
}
```
## Review point

> 어떤 부분에 리뷰어가 집중하면 좋을지(가이드라인 제시)

## Challenge point

> 어려웠던 점 (선택사항)

2023-08-02 14:28 UTC, hayeonn2 approved these changes

2023-08-02 14:28 UTC, hayeonn2 commented on app/components/Searchfield/Searchfield.tsx
> +          </svg>
이거 assets 폴더에 svg파일로 넣어서 Image로 불러오심이 어떨까요?

2023-08-02 14:30 UTC, hayeonn2 approved these changes

2023-08-02 14:30 UTC, hayeonn2 commented on app/components/Input/Input.tsx
> +        className="bg-Grayscale-5 w-[422px] h-[48px] pr-4 pt-[10px] pl-4 pb-[10px] outline-none rounded-[10px]"
className 동일하면 변수로 빼서 할당하는 방법도 좋을 것 같아요!

2023-08-02 15:39 UTC, UichaeHong commented on app/components/Searchfield/Searchfield.tsx
> +          </svg>
그렇게 해보겠습니다 !

2023-08-04 13:43 UTC, DoctorK4 requested changes

2023-08-05 16:58 UTC, UichaeHong commented on app/components/Input/Input.tsx
> +        <br />
수정했습니다 !

2023-08-05 17:02 UTC, UichaeHong commented on app/components/Input/Input.tsx
> +          placeholder="이메일 주소"
placeholder, type(text, password) , 그리고 input 위나 아래에  들어가는 text 변경할 수 있고  text color까지 default, blue, red로 기본값을 만들어서 사용자가 직접 설정할 수 있도록 수정했습니다

2023-08-05 17:05 UTC, UichaeHong commented on app/components/Input/Input.tsx
> +        className="bg-Grayscale-5 w-[422px] h-[48px] pr-4 pt-[10px] pl-4 pb-[10px] outline-none rounded-[10px]"
수정했습니다 !

2023-08-06 07:47 UTC, Zoey425 approved these changes

2023-08-06 14:35 UTC, merged